### ISSUE TITLE
Do input validation on request parameters

### ISSUE THREAD

**Issue by ajmcmiddlin** [zellige/hastile#12]
We currently don't do any input validation on request parameters. For example, we could check and provide nice errors when any of the following aren't met:
- [x] z, x, y are all natural
- [ ] z is below some max zoom level
- [ ] x and y are within range given zoom level
- [x] layer has configuration
- [x] sql is good and DB query is successful (depends on Hasql error reporting)

**Comment by ajmcmiddlin** [comment]
Can probably tick off the first three with a smart constructor on `Coordinates` type.

**Comment by newmana** [comment]
https://github.com/zellige/hastile/issues/11
