### ISSUE TITLE
Add load tests 

### ISSUE THREAD

**Issue by newmana** [zellige/hastile#14]

**Comment by ajmcmiddlin** [comment]
What sort of load tests did you have in mind @newmana? Something like hitting it with JMeter? Maybe put it on a VM and keep the numbers for later comparisons?

**Comment by newmana** [comment]
Just a giant GeoJSON file (production can render >1MB MVT files - 10s-100s MB GeoJSON), render it and make sure it doesn't crash Hastile and continually runs as fast as it does now if not faster.

**Comment by newmana** [comment]
The load tests are in zellige: https://github.com/zellige/zellige/tree/master/bench
