### ISSUE TITLE
Zoom dependant queries

### ISSUE THREAD

**Issue by newmana** [zellige/hastile#23]
Change the configuration file to create a pair of settings:
* Query
* Zoom level

The idea is given a zoom level call a specific query.

For example:
```
    "layer1": { 
      "queries": {
        "query": {
          "zoom": 1,
          "sql": "SELECT ST_AsGeoJSON(wkb_geometry), hstore(layer1_table)-'wkb_geometry'::text FROM layer1_table WHERE ST_Intersects(wkb_geometry, !bbox_4326!)"
        },
        "query": {
          "zoom": 7,
          "sql": "SELECT ST_AsGeoJSON(wkb_geometry), hstore(layer1_table)-'wkb_geometry'::text FROM layer1_table WHERE ST_Intersects(wkb_geometry, !bbox_4326!)"
        }
      }
      "last-modified": "2017-01-15T23:49:36Z"
    },
```

**Comment by newmana** [comment]
An alternative might be removing "queries" and just have query - with either a single query with sql and no zoom, or multiple query with zooms.

About 1 day.

**Comment by ajmcmiddlin** [comment]
Am I right in thinking that if you're specifying multiple queries then the SQL should be different? Example seems to have query repeated.

Also, I'm probably in favour of having the queries explicit.

**Comment by newmana** [comment]
We don't support queries anymore and did zoom dependent simplification instead.

"simplify": {
        "12": "douglas-peucker"
      }
