### ISSUE TITLE
Integration test doesn't work in Linux

### ISSUE THREAD

**Issue by newmana** [zellige/hastile#25]
Not sure what's causing this - potentially a different version of Mapnik producing slightly different results or a difference in OS (seems unlikely).

Maybe create semantic tests using: https://github.com/fosskers/vectortiles

As in check for name, features, etc, rather than binary comparison.

/cc @ajmccluskey

**Comment by ajmcmiddlin** [comment]
Might spit out the tile to disk and diff with the one on Mac to see what the difference is. Might be something simple.

In any event, a semantic test is probably better - I was looking for a quick test, and wanted to play with tasty-golden :p.

**Comment by ajmcmiddlin** [comment]
I've had a look at this. Checking counts for features of particular types (i.e. `Point`, `LineString`, or `Polygon` and properties shouldn't be too bad, but checking coordinates would be difficult given we'd have to project the integer values for the tile back into web mercator lat/lons. Doable, but hairy.

On the bright side, I imagine being able to go from MVT back to GeoJson is a nice thing to have. Especially if/when we break the MVT/geography stuff into its own library.

**Comment by newmana** [comment]
You could read in an MVT that's the expected values and compare it against the output MVT - that's all I was thinking - not GeoJSON == MVT.
