### ISSUE TITLE
All tile features need an ID field

### ISSUE THREAD

**Issue by ljnicol** [zellige/hastile#28]
This needs to be unique across all layers on the current hastile instance.

**Comment by ajmcmiddlin** [comment]
Unless I'm misunderstanding, I believe this is a data issue rather than a hastile issue. Your layer query can put all columns in a hstore, and those columns become properties on your tile. So as long as your query is carrying through the ID field or other data you want, you should be fine.

**Comment by ljnicol** [comment]
I agree actually - this is probably a data issue. We need to have an ID field that is unique across our data, and Hastile will work as required. Closing.
