### ISSUE TITLE
Hastile failing to render tiles

### ISSUE THREAD

**Issue by ljnicol** [zellige/hastile#33]
Error message:
```
libc++abi.dylib: terminating with uncaught exception of type mapnik::datasource_exception: geojson_datasource: Failed parse GeoJSON file from in-memory string
libc++abi.dylib: [1]    1711 abort      stack exec -- hastile --configFile ../sitewisely-web/config/hastile.config
```

**Comment by newmana** [comment]
This looks like a data or query error. Request the json version of the tile and take a look at it.

**Comment by newmana** [comment]
Attach what you can: geojson, data and query.

**Comment by ljnicol** [comment]
I've gone back and built before #29 was merged (I had to kill everything on my machine so I thought I might have a data error), but it seems to work fine. I think I've found the problem (in my materialised view creation): 
` CREATE MATERIALIZED VIEW layer1_table as SELECT st_asgeojson(layer_v5.wkb_geometry) AS geojson,
    layer_v5.wkb_geometry,
    (hstore(layer_v5.*) - 'wkb_geometry'::text) AS properties
   FROM layer_v5;`
Should be:
`CREATE MATERIALIZED VIEW layer1_table as SELECT jsonb_build_object(
    'type',      'Feature',
    'id',         ogc_fid,
    'geometry',   ST_AsGeoJSON(wkb_geometry)::jsonb,
    'properties', to_jsonb(row) - 'ogc_fid' - 'wkb_geometry'
)::json as geojson, row.wkb_geometry as wkb_geometry FROM (SELECT * FROM source_layer1_table) row;`

I think I just need to go through and update my materialised views as per the new spec.

**Comment by newmana** [comment]
Yeah - it was a breaking change.  One way we could improve it is to create release notes - versioned and dated - so you know what to change.

**Comment by newmana** [comment]
https://github.com/vlc/hastile/releases
