### ISSUE TITLE
Add buffer to bounding box for features in a tile

### ISSUE THREAD

**Issue by ajmcmiddlin** [zellige/hastile#41]
Features being rendered at the edge of a tile get clipped when `icon-allow-overlap` is enabled. To overcome the clipping, features at the edge of a tile boundary need to be rendered by the tiles on either side of the boundary. This way, when the marker is clipped when rendered on one tile, the other tile is also aware of the feature and renders the part that appears in its tile.

To achieve this, a buffer is added to vector tiles, so features not strictly in a tile, but near the boundary, are known and rendered by both tiles. It looks like mapnik has a default buffer of 128px for its vector tiles, but hastile does no buffering in its query, so the features aren't present in the data to be included in the tile buffer.

Some relevant issues:

 - https://github.com/mapbox/mapbox-gl-js/issues/2066
 - https://github.com/mapbox/mapbox-gl-js/issues/2706
 - https://github.com/mapbox/mapbox-gl-js/issues/3798

**Comment by newmana** [comment]
What's the requirements?  To set the buffer in the configuration file and it to be applied to both queries and mapnik?

**Comment by ajmcmiddlin** [comment]
I haven't thought it all through yet, but that's the idea. The alternative would be to use a default buffer that corresponds to mapnik's default, but I think having it configurable is important, as the size required is dependent on what and how you're rendering.
