### ISSUE TITLE
Cluster geojson point data

### ISSUE THREAD

**Issue by newmana** [zellige/hastile#42]
Build into serving point data - automatically create clusters of points.  For example, at a high zoom level you see 10 points, zoomed out they cluster to 1 point with the number 10 on it.

**Comment by ajmcmiddlin** [comment]
This would need front-end support as well right? If so, do we know what the interface is?

**Comment by newmana** [comment]
Based on our conversation add configuration options:
* Clustering radius.

Here's a good example:
https://gis.stackexchange.com/questions/11567/spatial-clustering-with-postgis

**Comment by ajmcmiddlin** [comment]
Again, as discussed off github, this could be achieved using zoom-dependent layers in mapbox's front-end library, and specifying cluster layers that can be used when zoomed out. The solution to this issue might then be:

 - Establish that we can do this
 - Write an example in the README (or spin off to a gh-pages site to host examples)

**Comment by newmana** [comment]
This requirement looks weird from the distance of time.

Mapbox has been doing this since 2016:
https://blog.mapbox.com/clustering-millions-of-points-on-a-map-with-supercluster-272046ec5c97

We also have requirement in zellige to remove duplicate points (which would would destroy clustering but is useful when you just want to show something exists - not how many - and not have cumulative values).

https://github.com/indicatrix/zellige/issues/11
