### ISSUE TITLE
Serve tileJSON for layers

### ISSUE THREAD

**Issue by ljnicol** [zellige/hastile#62]
Rather than using the list of tile urls in the styles, Hastile could generate a tileJSON, compliant with [here](https://github.com/mapbox/tilejson-spec/tree/master/2.2.0).

This would mean we could handle bounds, min and max zoom, attribution etc directly from Hastile, rather than having to add this data later.

**Comment by newmana** [comment]
Or https://github.com/mojodna/tapalcatl-2-spec

**Comment by newmana** [comment]
Example of use:
https://api.tiles.mapbox.com/v3/mapbox.geography-class.json
