### ISSUE TITLE
Source Layer type

### ISSUE THREAD

**Issue by newmana** [zellige/hastile#65]
Based on #63 we need to:

Create a layer type than just uses a SQL Table with the following properties:
- ogc_fid OR id column,
- wkb_geometry column (geometry type),
- Numeric types: integer, bigint, and real/float4,
- Character types: varchar.

The task is really to take this table and produce a (hs-geojson) GeoJSON that zellige can use.

**Comment by newmana** [comment]
This has a good example of how to create a query that produces a GeoJSON with a geometry and a list of properties https://postgis.net/docs/ST_AsGeoJSON.html

**Comment by dendrei** [comment]
Closed by 3ca1feacf2670ec0828fa713ad0bfbc9aabb2d7c
